#!/bin/bash
DATAFILE=~/money.csv

usage() {
	cat <<EOF
Simple finance tracking application.
Usage: money <account> <amount> <name>
       money -i
Options:
    -i -  Interactive mode. Reads records from stdin in form <amount> <name>,
          one for each line.
Interactive mode commands:
    account NAME - sets default account name so you wouldn't need to type it 
	             into every record.
    group NAME - start record group with name NAME. Each record will have the
                 same prefix 'NAME: '. Groups cannot be nested, each statement
                 will restart group.
    end -        end group mode.
EOF
}

add_record() {
	DATE=$(date +%FT%T)
	ACCOUNT=$1
	AMOUNT=$2
	shift
	shift
	NAME=$*

	if [ -z "$ACCOUNT" ]; then
		echo 'Account should not be empty.'
		return 1
	fi

	if echo "$ACCOUNT" | grep -q '[-+][0-9]\+[.][0-9]\{2\}'; then
		echo 'It seems you have missed account name.'
		return 1
	fi

	if echo "$ACCOUNT" | grep -q '^[A-Z]\+$'; then
		true
	else
		echo 'Account should consist only of uppercase letters.'
		return 1
	fi

	if echo $AMOUNT | grep -q '[-+][0-9]\+[.][0-9]\{2\}'; then
		true
	else
		echo 'Amount should be in form `*XXXXXX.CC`, where `*` should be either `+` for income or `-` for outcome.'
		return 1
	fi

	echo -e "${DATE},${ACCOUNT},${AMOUNT},${NAME}" >> "$DATAFILE"
}

if [ "$1" == '-i' ]; then
	group=''
	default_account=''
	while read command; do
		if echo "$command" | grep -q '^account .'; then
			default_account="$(echo "$command" | sed 's/^account //')"
		elif echo "$command" | grep -q '^group .'; then
			group="$(echo "$command" | sed 's/^group //'): "
		elif echo "$command" | grep -q '^end$'; then
			group=''
		else
			if [ -z "$default_account" ]; then
				account=$(echo "$command" | sed 's/^\([^ ]\+\) .*/\1/')
					command=$(echo "$command" | sed 's/^[^ ]\+ \+\(.*\)/\1/')
			else
				account="$default_account"
			fi
			amount=$(echo "$command" | sed 's/\([^ ]\+\) .*/\1/')
				command=$(echo "$command" | sed 's/^[^ ]\+ \+\(.*\)/\1/')
			name="$command"
			add_record "$account" "$amount" "${group}${name}"
		fi
	done
elif [ "$1" == "--help" ]; then
	usage
elif [ -z "$2" ]; then
	usage
	exit 1
else
	add_record "$@"
fi
