#!/bin/bash
if [ -z "$2" ]; then
	echo 'Usage: money <amount> <name>'
	exit 1
fi

DATAFILE=~/money.csv

DATE=$(date +%FT%T)
AMOUNT=$1
NAME=$2

if echo $AMOUNT | grep -q '[-+][0-9]\+[.][0-9]\{2\}'; then
	true;
else
	echo 'Amount should be in form `*XXXXXX.CC`, where `*` should be either `+` for income or `-` for outcome.'
	exit 1
fi

echo -e "${DATE},${AMOUNT},${NAME}" >> "$DATAFILE"
