#!/bin/bash
DATAFILE=~/money.csv

usage() {
	cat <<EOF
Simple finance tracking application.
Usage: money <amount> <name>
       money -i
Options:
    -i -  Interactive mode. Reads records from stdin in form <amount> <name>,
          one for each line.
EOF
}

add_record() {
	DATE=$(date +%FT%T)
	AMOUNT=$1
	shift
	NAME=$*

	if echo $AMOUNT | grep -q '[-+][0-9]\+[.][0-9]\{2\}'; then
		true;
	else
		echo 'Amount should be in form `*XXXXXX.CC`, where `*` should be either `+` for income or `-` for outcome.'
		return 1
	fi

	echo -e "${DATE},${AMOUNT},${NAME}" >> "$DATAFILE"
}

if [ "$1" == '-i' ]; then
	while read line; do
		add_record $line
	done
elif [ "$1" == "--help" ]; then
	usage
elif [ -z "$2" ]; then
	usage
	exit 1
else
	add_record "$@"
fi
